BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

/* -------------------------------------------------------------------------- */
/* LOOKUPS                                                                     */
/* -------------------------------------------------------------------------- */

CREATE TABLE IF NOT EXISTS public.recut_reasons (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text UNIQUE,
  label text NOT NULL UNIQUE,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.recut_requested_departments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text UNIQUE,
  label text NOT NULL UNIQUE,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.recut_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  item_code text NOT NULL UNIQUE,
  description text,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

/* -------------------------------------------------------------------------- */
/* MAIN TABLE                                                                  */
/* -------------------------------------------------------------------------- */

CREATE TABLE IF NOT EXISTS public.recut_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  recut_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,

  requested_at timestamptz NOT NULL DEFAULT now(),
  requested_date date NOT NULL DEFAULT ((now() AT TIME ZONE 'America/Chicago')::date),
  requested_time time(0) NOT NULL DEFAULT ((now() AT TIME ZONE 'America/Chicago')::time(0)),

  requested_by_user_id text,
  requested_by_username text,
  requested_by_name text NOT NULL,
  requested_by_employee_number integer,

  requested_department text NOT NULL,

  sales_order text NOT NULL,
  design_name text NOT NULL,
  recut_reason text NOT NULL,
  detail_number integer NOT NULL,
  cap_style text NOT NULL,
  pieces integer NOT NULL,
  operator text NOT NULL,
  deliver_to text NOT NULL,

  supervisor_approved boolean NOT NULL DEFAULT false,
  supervisor_approved_at timestamptz,
  supervisor_approved_by text,

  warehouse_printed boolean NOT NULL DEFAULT false,
  warehouse_printed_at timestamptz,
  warehouse_printed_by text,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT recut_requests_sales_order_chk
    CHECK (sales_order ~ '^[0-9]{7}\.[0-9]{3}$'),

  CONSTRAINT recut_requests_detail_number_chk
    CHECK (detail_number >= 0),

  CONSTRAINT recut_requests_pieces_chk
    CHECK (pieces > 0)
);

/* -------------------------------------------------------------------------- */
/* INDEXES                                                                     */
/* -------------------------------------------------------------------------- */

CREATE INDEX IF NOT EXISTS idx_recut_reasons_sort
  ON public.recut_reasons (is_active, sort_order, label);

CREATE INDEX IF NOT EXISTS idx_recut_requested_departments_sort
  ON public.recut_requested_departments (is_active, sort_order, label);

CREATE INDEX IF NOT EXISTS idx_recut_items_sort
  ON public.recut_items (is_active, sort_order, item_code);

CREATE INDEX IF NOT EXISTS idx_recut_requests_requested_at
  ON public.recut_requests (requested_at DESC);

CREATE INDEX IF NOT EXISTS idx_recut_requests_requested_by_employee_number
  ON public.recut_requests (requested_by_employee_number);

CREATE INDEX IF NOT EXISTS idx_recut_requests_requested_by_username
  ON public.recut_requests (requested_by_username);

CREATE INDEX IF NOT EXISTS idx_recut_requests_status_flags
  ON public.recut_requests (supervisor_approved, warehouse_printed);

CREATE INDEX IF NOT EXISTS idx_recut_requests_sales_order
  ON public.recut_requests (sales_order);

CREATE INDEX IF NOT EXISTS idx_recut_requests_detail_number
  ON public.recut_requests (detail_number);

CREATE INDEX IF NOT EXISTS idx_recut_requests_requested_department
  ON public.recut_requests (requested_department);

CREATE INDEX IF NOT EXISTS idx_recut_requests_recut_reason
  ON public.recut_requests (recut_reason);

CREATE INDEX IF NOT EXISTS idx_recut_requests_cap_style
  ON public.recut_requests (cap_style);

/* -------------------------------------------------------------------------- */
/* TRIGGERS                                                                    */
/* -------------------------------------------------------------------------- */

DROP TRIGGER IF EXISTS trg_recut_reasons_updated_at ON public.recut_reasons;
CREATE TRIGGER trg_recut_reasons_updated_at
BEFORE UPDATE ON public.recut_reasons
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_recut_requested_departments_updated_at ON public.recut_requested_departments;
CREATE TRIGGER trg_recut_requested_departments_updated_at
BEFORE UPDATE ON public.recut_requested_departments
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_recut_items_updated_at ON public.recut_items;
CREATE TRIGGER trg_recut_items_updated_at
BEFORE UPDATE ON public.recut_items
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_recut_requests_updated_at ON public.recut_requests;
CREATE TRIGGER trg_recut_requests_updated_at
BEFORE UPDATE ON public.recut_requests
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

COMMIT;